// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxKo8KMi0eo3u7nX8mUMf55UJ-KragFBY',
    appId: '1:587896639408:web:8720cf6b834eec555f1075',
    messagingSenderId: '587896639408',
    projectId: 'tubes-mobdev',
    authDomain: 'tubes-mobdev.firebaseapp.com',
    storageBucket: 'tubes-mobdev.firebasestorage.app',
    measurementId: 'G-X5M7P7PZ4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBddm3HAQSqiueOC5Wd7DgyYItetDDbzvc',
    appId: '1:587896639408:android:8c5d746bdb7986fb5f1075',
    messagingSenderId: '587896639408',
    projectId: 'tubes-mobdev',
    storageBucket: 'tubes-mobdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZZrPJ8NgEvELrSSj4DVf4Avi7BDZqZ2A',
    appId: '1:587896639408:ios:3017d40243b978e95f1075',
    messagingSenderId: '587896639408',
    projectId: 'tubes-mobdev',
    storageBucket: 'tubes-mobdev.firebasestorage.app',
    iosBundleId: 'com.tokoroti.tokoRoti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYz-RmD-cJ-NR9-skGMfcuHEgVZog-gMw',
    appId: '1:861140304120:ios:40f686061d7175ab9dfb0d',
    messagingSenderId: '861140304120',
    projectId: 'toko-roti-4b40d',
    storageBucket: 'toko-roti-4b40d.firebasestorage.app',
    iosBundleId: 'com.tokoroti.tokoRoti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDASATNkfC7BsgJMph5M5Q9SUebXoWkoKs',
    appId: '1:861140304120:web:f6462b761994e8129dfb0d',
    messagingSenderId: '861140304120',
    projectId: 'toko-roti-4b40d',
    authDomain: 'toko-roti-4b40d.firebaseapp.com',
    storageBucket: 'toko-roti-4b40d.firebasestorage.app',
    measurementId: 'G-M6NLTF0DEW',
  );
}